name: Hello World

on:
  push:
    branches:
      - check_python_version

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Hello World
      run: echo "Hello, World!"
