name: check_syntax

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version:
          - 3.9
          - 3.10
          - 3.11

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python (3.9 and 3.11)
        if: matrix.python-version != '3.10'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Set up Python (3.10)
        if: matrix.python-version == '3.10'
        run: echo "Python 3.10 is not supported on Ubuntu."

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install flake8
          python -m pip install unittest

      - name: Display Python version
        run: python --version

      - name: Run flake8
        run: flake8 .

      - name: Run unittest
        run: python -m unittest discover -v
