name: check_syntax

on:
  push:

jobs:
  syntax-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip
        pip --version

    - name: Install dependencies
      run: |
        pip install flake8
        pip install unittest

    - name: Display Python version
      run: python --version

    - name: Run flake8 (code style check)
      run: flake8 .

    - name: Run unit tests
      run: python -m unittest discover

