name: check_syntax

on:
  push:
    branches:
      - main  # Zaktualizuj gałąź na odpowiednią, jeśli to konieczne

jobs:
  syntax_check:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - 3.9
          - 3.10
          - 3.11

    jobs:
      - name: Check Syntax
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]
            python-version:
              - 3.9
              - 3.10
              - 3.11

        steps:
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
              architecture: 'x64'

          - name: Update pip
            run: |
              python -m pip install --upgrade pip

          - name: Install flake8
            run: |
              pip install flake8

          - name: Display Python version
            run: |
              python --version

          - name: Run flake8
            run: |
              flake8

          - name: Run unittest
            run: |
              # Uruchomienie testów z użyciem unittest (nie ma potrzeby instalacji unittest, ponieważ jest częścią standardowej biblioteki Pythona)
              python -m unittest discover

      - name: Check Syntax (Windows)
        runs-on: windows-latest
        strategy:
          matrix:
            os: [windows-latest]
            python-version:
              - 3.9
              - 3.11

        steps:
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
              architecture: 'x64'

          - name: Update pip
            run: |
              python -m pip install --upgrade pip

          - name: Install flake8
            run: |
              pip install flake8

          - name: Display Python version
            run: |
              python --version

          - name: Run flake8
            run: |
              flake8

          - name: Run unittest
            run: |
              # Uruchomienie testów z użyciem unittest (nie ma potrzeby instalacji unittest, ponieważ jest częścią standardowej biblioteki Pythona)
              python -m unittest discover
