#Nazwa workflow
name: check_syntax2

on:
  push:
    branches:
      - main

#Wykorzystanie opcji matrix zeby zastosowa podane wersje pythona dla podanych systemow
jobs:
  syntax_check:
    runs-on: ${{ matrix.os }}

#Wyznaczenie dla jakich systemow bedziemy wykonywac kolejne kroki
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
        exclude:
          - os: ubuntu-latest
            python-version: 3.10
#Wykluczenie pythona w wersji 3.10 dla ubuntu

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

#Aktualizacja pip
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
#Instalacja flake8
      - name: Install flake8
        run: |
          pip install flake8
#Wyswietlenie wersji pythona
      - name: Display Python version
        run: |
          python --version
#Analiza kodu za pomoca flake8
      - name: Run flake8
        run: |
          flake8
          

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run tests
        run: |
          python3 -m unittest discover -v ./Laboratorium_nr4
